apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/johnbieren/release-service/config/default?ref=ab5215d4749304726b98ef5d4868bef61dae436f
  - release_service_config.yaml
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/jbieren/release-service
    newTag: konflux8327_2
namespace: release-service
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: sealights-token-patch.yaml
