apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/johnbieren/release-service/config/default?ref=ba7d9d726ed64ea85897ee0f5745fa40bbd7f810
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/jbieren/release-service
    newTag: kfluxbugs1921_3
namespace: release-service
